<a href="https://colab.research.google.com/github/ishwaridhage10-cpu/NumPy-Project/blob/main/sepical_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import files
uploaded=files.upload()

Saving players.csv to players.csv

In [3]:
filepath="/content/players.csv"

In [5]:
import pandas as pd
df=pd.read_csv(filepath)

In [8]:
df.head()

,player,team,team_country,position,age,birth_year,club,games,games_starts,minutes,...,gk_wins,gk_ties,gk_losses,gk_clean_sheets,gk_clean_sheets_pct,gk_pens_att,gk_pens_allowed,gk_pens_saved,gk_pens_missed,gk_pens_save_pct
0,Achref Abada,Algeria,Algeria,DF,27-020,1999,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Adil Boulbina,Algeria,Algeria,FW,23-064,2003,NaN,2,0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Amine Gouiri,Algeria,Algeria,FW,26-139,2000,Marseille,4,3,251.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Anis Hadj Moussa,Algeria,Algeria,MF,24-144,2002,Feyenoord,3,1,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aïssa Mandi,Algeria,Algeria,DF,34-256,1991,Lille,4,4,360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.tail()

,player,team,team_country,position,age,birth_year,club,games,games_starts,minutes,...,gk_wins,gk_ties,gk_losses,gk_clean_sheets,gk_clean_sheets_pct,gk_pens_att,gk_pens_allowed,gk_pens_saved,gk_pens_missed,gk_pens_save_pct
1242,Rustam Ashurmatov,Uzbekistan,Uzbekistan,DF,29-363,1996,Esteghlal,3,3,256.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1243,Sherzod Esanov,Uzbekistan,Uzbekistan,MF,23-154,2003,NaN,1,0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1244,Sherzod Nasrullaev,Uzbekistan,Uzbekistan,"DF,MF",27-347,1998,NaN,3,3,180.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1245,Umar Eshmurodov,Uzbekistan,Uzbekistan,DF,33-217,1992,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1246,Utkir Yusupov,Uzbekistan,Uzbekistan,GK,35-182,1991,NaN,1,1,90.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [9]:
df.shape

(1247, 72)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1247 entries, 0 to 1246
Data columns (total 72 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   player                      1247 non-null   object
 1   team                        1247 non-null   object
 2   team_country                1247 non-null   object
 3   position                    1247 non-null   object
 4   age                         1247 non-null   object
 5   birth_year                  1247 non-null   int64
 6   club                        891 non-null    object
 7   games                       1247 non-null   int64
 8   games_starts                1247 non-null   int64
 9   minutes                     1023 non-null   float64
 10  minutes_90s                 1023 non-null   float64
 11  goals                       1023 non-null   float64
 12  assists                     1023 non-null   float64
 13  goals_assists               1023 non-null   float64
 14  goals_pens                  1023 non-null   float64
 15  pens_made                   1023 non-null   float64
 16  pens_att                    1023 non-null   float64
 17  cards_yellow                1023 non-null   float64
 18  cards_red                   1023 non-null   float64
 19  goals_per90                 1023 non-null   float64
 20  assists_per90               1023 non-null   float64
 21  goals_assists_per90         1023 non-null   float64
 22  goals_pens_per90            1023 non-null   float64
 23  goals_assists_pens_per90    1023 non-null   float64
 24  shots                       1023 non-null   float64
 25  shots_on_target             1023 non-null   float64
 26  shots_on_target_pct         662 non-null    float64
 27  shots_per90                 1023 non-null   float64
 28  shots_on_target_per90       1023 non-null   float64
 29  goals_per_shot              662 non-null    float64
 30  goals_per_shot_on_target    378 non-null    float64
 31  minutes_per_game            1023 non-null   float64
 32  minutes_pct                 1023 non-null   float64
 33  minutes_per_start           768 non-null    float64
 34  games_complete              1247 non-null   int64
 35  games_subs                  1247 non-null   int64
 36  minutes_per_sub             542 non-null    float64
 37  unused_subs                 1247 non-null   int64
 38  points_per_game             1023 non-null   float64
 39  on_goals_for                1023 non-null   float64
 40  on_goals_against            1023 non-null   float64
 41  plus_minus                  1023 non-null   float64
 42  plus_minus_per90            1023 non-null   float64
 43  plus_minus_wowy             900 non-null    float64
 44  cards_yellow_red            1023 non-null   float64
 45  fouls                       1023 non-null   float64
 46  fouled                      1023 non-null   float64
 47  offsides                    1023 non-null   float64
 48  crosses                     1023 non-null   float64
 49  interceptions               1023 non-null   float64
 50  tackles_won                 1023 non-null   float64
 51  pens_won                    0 non-null      float64
 52  pens_conceded               0 non-null      float64
 53  own_goals                   1023 non-null   float64
 54  gk_games                    60 non-null     float64
 55  gk_games_starts             60 non-null     float64
 56  gk_minutes                  60 non-null     float64
 57  gk_goals_against            60 non-null     float64
 58  gk_goals_against_per90      60 non-null     float64
 59  gk_shots_on_target_against  60 non-null     float64
 60  gk_saves                    60 non-null     float64
 61  gk_save_pct                 57 non-null     float64
 62  gk_wins                     60 non-null     float64
 63  gk_ties                     60 non-null     float64
 64  gk_losses                   60 non-null     float64
 65  gk_clean_sheets             60 non-null     float64
 66  gk_clean_sheets_pct         57 non-null     float64
 67  gk_pens_att                 60 non-null     float64
 68  gk_pens_allowed             60 non-null     float64
 69  gk_pens_saved               60 non-null     float64
 70  gk_pens_missed              60 non-null     float64
 71  gk_pens_save_pct            11 non-null     float64
dtypes: float64(60), int64(6), object(6)
memory usage: 701.6+ KB

In [12]:
df.describe()

,birth_year,games,games_starts,minutes,minutes_90s,goals,assists,goals_assists,goals_pens,pens_made,...,gk_wins,gk_ties,gk_losses,gk_clean_sheets,gk_clean_sheets_pct,gk_pens_att,gk_pens_allowed,gk_pens_saved,gk_pens_missed,gk_pens_save_pct
count,1247.000000,1247.000000,1247.000000,1023.000000,1023.000000,1023.000000,1023.000000,1023.000000,1023.000000,1023.000000,...,60.000000,60.000000,60.000000,60.000000,57.000000,60.000000,60.000000,60.000000,60.000000,11.000000
mean,1998.036889,2.277466,1.587811,177.093842,1.966960,0.242424,0.185728,0.428152,0.231672,0.010753,...,1.116667,0.766667,1.116667,0.850000,23.770175,0.233333,0.183333,0.033333,0.016667,18.181818
std,4.257022,1.487777,1.543415,120.837695,1.341576,0.693751,0.510853,0.942822,0.662154,0.103187,...,1.290009,0.889995,0.940459,1.070799,28.956013,0.499717,0.469102,0.181020,0.129099,40.451992
min,1982.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1995.000000,1.000000,0.000000,67.500000,0.750000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1998.000000,3.000000,1.000000,173.000000,1.900000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2001.000000,4.000000,3.000000,270.000000,3.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,2.000000,1.000000,2.000000,2.000000,50.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2008.000000,5.000000,5.000000,480.000000,5.300000,7.000000,5.000000,9.000000,7.000000,1.000000,...,5.000000,3.000000,3.000000,4.000000,100.000000,2.000000,2.000000,1.000000,1.000000,100.000000

In [14]:
df.columns

Index(['player', 'team', 'team_country', 'position', 'age', 'birth_year',
       'club', 'games', 'games_starts', 'minutes', 'minutes_90s', 'goals',
       'assists', 'goals_assists', 'goals_pens', 'pens_made', 'pens_att',
       'cards_yellow', 'cards_red', 'goals_per90', 'assists_per90',
       'goals_assists_per90', 'goals_pens_per90', 'goals_assists_pens_per90',
       'shots', 'shots_on_target', 'shots_on_target_pct', 'shots_per90',
       'shots_on_target_per90', 'goals_per_shot', 'goals_per_shot_on_target',
       'minutes_per_game', 'minutes_pct', 'minutes_per_start',
       'games_complete', 'games_subs', 'minutes_per_sub', 'unused_subs',
       'points_per_game', 'on_goals_for', 'on_goals_against', 'plus_minus',
       'plus_minus_per90', 'plus_minus_wowy', 'cards_yellow_red', 'fouls',
       'fouled', 'offsides', 'crosses', 'interceptions', 'tackles_won',
       'pens_won', 'pens_conceded', 'own_goals', 'gk_games', 'gk_games_starts',
       'gk_minutes', 'gk_goals_against', 'gk_goals_against_per90',
       'gk_shots_on_target_against', 'gk_saves', 'gk_save_pct', 'gk_wins',
       'gk_ties', 'gk_losses', 'gk_clean_sheets', 'gk_clean_sheets_pct',
       'gk_pens_att', 'gk_pens_allowed', 'gk_pens_saved', 'gk_pens_missed',
       'gk_pens_save_pct'],
      dtype='object')

In [15]:
df.dtypes

player               object
team                 object
team_country         object
position             object
age                  object
                     ...
gk_pens_att         float64
gk_pens_allowed     float64
gk_pens_saved       float64
gk_pens_missed      float64
gk_pens_save_pct    float64
Length: 72, dtype: object

In [16]:
df.isnull().sum()

player                 0
team                   0
team_country           0
position               0
age                    0
                    ...
gk_pens_att         1187
gk_pens_allowed     1187
gk_pens_saved       1187
gk_pens_missed      1187
gk_pens_save_pct    1236
Length: 72, dtype: int64

In [17]:
df.nunique()

player              1246
team                  48
team_country          48
position               9
age                 1114
                    ...
gk_pens_att            3
gk_pens_allowed        3
gk_pens_saved          2
gk_pens_missed         2
gk_pens_save_pct       2
Length: 72, dtype: int64

In [18]:
df.sample(5)

,player,team,team_country,position,age,birth_year,club,games,games_starts,minutes,...,gk_wins,gk_ties,gk_losses,gk_clean_sheets,gk_clean_sheets_pct,gk_pens_att,gk_pens_allowed,gk_pens_saved,gk_pens_missed,gk_pens_save_pct
1205,Joaquín Piquerez,Uruguay,Uruguay,"DF,MF",27-315,1998,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
682,Jo Hyeon-woo,Korea Republic,Korea Republic,GK,34-283,1991,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
696,Park Jinseob,Korea Republic,Korea Republic,"DF,MF",30-255,1995,Zhejiang,2,0,32.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1055,Nico Williams,Spain,Spain,MF,23-358,2002,Athletic Club,3,0,48.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
758,Donyell Malen,Netherlands,Netherlands,FW,27-177,1999,Roma,3,3,185.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df.value_counts()

Series([], Name: count, dtype: int64)